classdef waveDB
    %WAVEDB Database layer specifically for interacting with the wave
    %database
    %
    %   Detailed explanation goes here
    
    properties
        con;        % database connection handle
        
    end
    
    methods
        function db = waveDB(dbconfig)
            db.con = database(dbconfig.database,dbconfig.username,...
                dbconfig.password,dbconfig.jdbcDriver,dbconfig.driverURL);
            setdbprefs('DataReturnFormat','structure');
        end
        function dField = selectSpectra(db,source,tBegin,tEnd,location)
            if(nargin<2)
                error(['Must provide a source name, use wavedb.showSources'...
                    ' to see a list of the possible source names']);
            end
            sql = ['SELECT  ',...
                '  tblwave.wavdatetime,         ',...
                '  tblwave.wavspectra,          ',...
                '  tblwave.wavheight,           ',...
                '  tblwave.wavpeakdir,          ',...
                '  tblwave.wavpeakperiod,       ',...
                '  ST_X(tblwave.wavlocation),   ',...
                '  ST_Y(tblwave.wavlocation),   ',...
                '  tblspectrabin.spcfreq,       ',...
                '  tblspectrabin.spcdir,        ',...
                '  tblsource.srcname,           ',...
                '  tblsource.srcconfig,         ',...
                '  tblsource.srcbeginexecution, ',...
                '  tblsource.srcendexecution,   ',...
                '  tblsource.srcsourcetypeid    ',...
                ' FROM                          ',...
                '  public.tblwave,              ',...
                '  public.tblspectrabin,        ',...
                '  public.tblsource             ',...
                ' WHERE                         ',...
                '  tblwave.wavspectrabinid = tblspectrabin.spcid AND ',...
                '  tblwave.wavsourceid = tblsource.srcid',...
                ' AND tblsource.srcname = ''',source,''''];
            
            if(nargin>2)
                sql = [sql,' AND tblwave.wavdatetime >= ''',...
                    datestr(tBegin,'yyyy-mm-dd HH:MM:SS'),''''];
            end
            if(nargin>3)
                sql = [sql,' AND tblwave.wavdatetime <= ''',...
                    datestr(tEnd,'yyyy-mm-dd HH:MM:SS'),''''];
            end
            
            rawspec = fetch(db.con,sql);
            if(size(rawspec,1)==0)
                error('Empty result set found')
            end
            n = size(rawspec.st_x,1);
            spec(n) = spectra;
            for i=1:n
                spec(i) = spectra(rawspec.srcname(i),...
                    rawspec.wavdatetime(i),...
                    [rawspec.st_x(i),rawspec.st_y(i)],...
                    double(rawspec.wavspectra{i}.getArray()),...
                    double(rawspec.spcfreq{i}.getArray()),...
                    double(rawspec.spcdir{i}.getArray()));
            end
            dField = dataField(spec);
        end
        function names = showSources(db)
            sql = ['SELECT  ',...
                '  DISTINCT ON(src.srcid)   ',...
                '  src.srcid,               ',...
                '  src.srcname,             ',...
                '  sty.sourcetypename,      ',...
                '  wav.wavid,               ',...
                '  win.winid,               ',...
                '  cur.curid,               ',...
                '  bat.batid                ',...
                'FROM                       ',...
                '  public.tblsource src     ',...
                'LEFT JOIN                  ',...
                '  public.tblwave wav    ON src.srcid=wav.wavsourceid ',...
                'LEFT JOIN                  ',...
                '  public.tblwind win    ON src.srcid=win.winsourceid ',...
                'LEFT JOIN                  ',...
                '  public.tblcurrent cur ON src.srcid=cur.cursourceid ',...
                'LEFT JOIN                  ',...
                '  public.tblbathy bat   ON src.srcid=bat.batsourceid ',...
                'LEFT JOIN                  ',...
                '  public.tblsourcetype sty ON src.srcsourcetypeid=sty.sourcetypeid',...
                'ORDER BY sty.sourcetypename'
                ];
            rawnames = fetch(db.con,sql);
            m = size(rawnames.srcid,1);
            dat = cell(m,6);
            for i=1:m
                dat(i,1:2) = {char(rawnames.srcname(i)),...
                    char(rawnames.sourcetypename(i))};
                if(strcmp(rawnames.wavid(i),'null'))
                    dat(i,3) = {0};
                else
                    dat(i,3) = {1};
                end
                if(strcmp(rawnames.winid(i),'null'))
                    dat(i,4) = {0};
                else
                    dat(i,4) = {1};
                end
                if(strcmp(rawnames.curid(i),'null'))
                    dat(i,5) = {0};
                else
                    dat(i,5) = {1};
                end
                if(strcmp(rawnames.batid(i),'null'))
                    dat(i,6) = {0};
                else
                    dat(i,6) = {1};
                end
            end
            vertPerRecord =  20;
            f = figure('Position',[200 200 800 130+m*vertPerRecord]);
            cnames = {'Source Name','Source Type','Wave Spectra','Wind','Current','Bathymetry'};
            columnformat = {'char', 'char', 'logical','logical','logical','logical'};
            t = uitable('Parent',f,'Data',dat,'ColumnName',cnames,... 
            'Position',[20 20 760 80+m*vertPerRecord]);
            set(t,'ColumnWidth',{170,170,90,90,90,90})
        end
    end
end